services:
  db:
    image: postgres:15
    container_name: postgres_db_customer
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customers_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d customers_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  customers:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customers_service
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

volumes:
  db_data:


networks:
  app_network:
    external: true
