services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  inventory:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_service
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5002:5000"
    depends_on:
      - db

volumes:
  db_data:
