services:
  db:
    image: postgres:15
    container_name: postgres_db_reviews
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reviews_db
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d reviews_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  reviews:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reviews_service
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      CUSTOMERS_SERVICE_URL: http://customers_service:5000
      INVENTORY_SERVICE_URL: http://inventory_service:5000
    ports:
      - "5004:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

volumes:
  db_data:


networks:
  app_network:
    external: true
