services:
  db:
    image: postgres:15
    container_name: postgres_db_sales
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales_db
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  sales:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales_service
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      CUSTOMERS_SERVICE_URL: http://customers_service:5000
      INVENTORY_SERVICE_URL: http://inventory_service:5000
    ports:
      - "5003:5000"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    external: true
